// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfnMIptk4OzFCnfIjmHgq3aEyoHR7C9U',
    appId: '1:1069102301689:web:afdc9eaab0377a63687d28',
    messagingSenderId: '1069102301689',
    projectId: 'pushme-dfeb5',
    authDomain: 'pushme-dfeb5.firebaseapp.com',
    databaseURL: 'https://pushme-dfeb5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushme-dfeb5.appspot.com',
    measurementId: 'G-Y9WKMT6PNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBISpHerLOQGZ9Gh6SfztbMLDVItAUukVY',
    appId: '1:1069102301689:android:49f62e78e1352e00687d28',
    messagingSenderId: '1069102301689',
    projectId: 'pushme-dfeb5',
    databaseURL: 'https://pushme-dfeb5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushme-dfeb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOePhYOHk3fyaqObp06YI3Rcr0750wUas',
    appId: '1:1069102301689:ios:22eac8ae6152745a687d28',
    messagingSenderId: '1069102301689',
    projectId: 'pushme-dfeb5',
    databaseURL: 'https://pushme-dfeb5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushme-dfeb5.appspot.com',
    iosClientId: '1069102301689-b1r8e5677cn1spr287qfu27bamuj2nph.apps.googleusercontent.com',
    iosBundleId: 'ch.pushme',
  );
}
